
DROP TABLE IF EXISTS bigint_test;

CREATE table bigint_test (
  id INTEGER NOT NULL AUTO_INCREMENT,
  input_string VARCHAR(255) NOT NULL,
  input_number BIGINT(40) NOT NULL,
  size_1 BIGINT(1) NOT NULL,
  size_1u BIGINT(1) UNSIGNED NOT NULL,
  size_2 BIGINT(2) NOT NULL,
  size_2u BIGINT(2) UNSIGNED NOT NULL,
  size_3 BIGINT(3) NOT NULL,
  size_3u BIGINT(3) UNSIGNED NOT NULL,
  size_4 BIGINT(4) NOT NULL,
  size_4u BIGINT(4) UNSIGNED NOT NULL,
  size_5 BIGINT(5) NOT NULL,
  size_5u BIGINT(5) UNSIGNED NOT NULL,
  size_6 BIGINT(6) NOT NULL,
  size_6u BIGINT(6) UNSIGNED NOT NULL,
  size_7 BIGINT(7) NOT NULL,
  size_7u BIGINT(7) UNSIGNED NOT NULL,
  size_8 BIGINT(8) NOT NULL,
  size_8u BIGINT(8) UNSIGNED NOT NULL,
  size_9 BIGINT(9) NOT NULL,
  size_9u BIGINT(9) UNSIGNED NOT NULL,
  size_10 BIGINT(10) NOT NULL,
  size_10u BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);
