
DROP TABLE IF EXISTS integer_test;

CREATE table integer_test (
  id INTEGER NOT NULL AUTO_INCREMENT,
  input_string VARCHAR(255) NOT NULL,
  input_number BIGINT(40) NOT NULL,
  size_1 INTEGER(1) NOT NULL,
  size_1u INTEGER(1) UNSIGNED NOT NULL,
  size_2 INTEGER(2) NOT NULL,
  size_2u INTEGER(2) UNSIGNED NOT NULL,
  size_3 INTEGER(3) NOT NULL,
  size_3u INTEGER(3) UNSIGNED NOT NULL,
  size_4 INTEGER(4) NOT NULL,
  size_4u INTEGER(4) UNSIGNED NOT NULL,
  size_5 INTEGER(5) NOT NULL,
  size_5u INTEGER(5) UNSIGNED NOT NULL,
  size_6 INTEGER(6) NOT NULL,
  size_6u INTEGER(6) UNSIGNED NOT NULL,
  size_7 INTEGER(7) NOT NULL,
  size_7u INTEGER(7) UNSIGNED NOT NULL,
  size_8 INTEGER(8) NOT NULL,
  size_8u INTEGER(8) UNSIGNED NOT NULL,
  size_9 INTEGER(9) NOT NULL,
  size_9u INTEGER(9) UNSIGNED NOT NULL,
  size_10 INTEGER(10) NOT NULL,
  size_10u INTEGER(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);
