
DROP TABLE IF EXISTS smallint_test;

CREATE table smallint_test (
  id INTEGER NOT NULL AUTO_INCREMENT,
  input_string VARCHAR(255) NOT NULL,
  input_number BIGINT(40) NOT NULL,
  size_1 SMALLINT(1) NOT NULL,
  size_1u SMALLINT(1) UNSIGNED NOT NULL,
  size_2 SMALLINT(2) NOT NULL,
  size_2u SMALLINT(2) UNSIGNED NOT NULL,
  size_3 SMALLINT(3) NOT NULL,
  size_3u SMALLINT(3) UNSIGNED NOT NULL,
  size_4 SMALLINT(4) NOT NULL,
  size_4u SMALLINT(4) UNSIGNED NOT NULL,
  size_5 SMALLINT(5) NOT NULL,
  size_5u SMALLINT(5) UNSIGNED NOT NULL,
  size_6 SMALLINT(6) NOT NULL,
  size_6u SMALLINT(6) UNSIGNED NOT NULL,
  size_7 SMALLINT(7) NOT NULL,
  size_7u SMALLINT(7) UNSIGNED NOT NULL,
  size_8 SMALLINT(8) NOT NULL,
  size_8u SMALLINT(8) UNSIGNED NOT NULL,
  size_9 SMALLINT(9) NOT NULL,
  size_9u SMALLINT(9) UNSIGNED NOT NULL,
  size_10 SMALLINT(10) NOT NULL,
  size_10u SMALLINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);
